name: Comment Linked Issues
description: Comment on issues referenced by commit messages when CI succeeds
inputs: {}
runs:
  using: composite
  steps:
    - name: Comment on linked issues
      uses: actions/github-script@v7
      with:
        script: |
          const { join } = await import('path');
          const { default: run } = await import(join(process.env.GITHUB_WORKSPACE, '.github', 'actions', 'comment-linked-issues', 'index.js'));
          await run({ github, context, core });
